spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: developer
    url: jdbc:mysql://localhost:3306/code_buffer_db
    password: '1234567'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
